# Generated by Django 4.2 on 2026-06-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_add_years_of_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="current_ctc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="education",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="candidate",
            name="expected_ctc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="notice_period_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
