# Generated by Django 4.2 on 2026-06-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_add_ctc_notice_education"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("female", "Female"),
                    ("male", "Male"),
                    ("non_binary", "Non-binary"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
