# Generated by Django 4.2 on 2026-06-21 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("single", "Single"), ("bulk", "Bulk")],
                        default="single",
                        max_length=10,
                    ),
                ),
                ("purpose", models.CharField(max_length=500)),
                ("tone", models.CharField(max_length=20)),
                ("length", models.CharField(max_length=20)),
                ("recipient", models.CharField(blank=True, max_length=200)),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("body", models.TextField(blank=True)),
                ("bulk_results", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
