# Generated by Django 4.2 on 2026-06-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_generatedemail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sentemail",
            name="related_candidate",
        ),
        migrations.RemoveField(
            model_name="sentemail",
            name="related_job",
        ),
        migrations.RemoveField(
            model_name="sentemail",
            name="sent_by",
        ),
        migrations.RemoveField(
            model_name="sentemail",
            name="template",
        ),
        migrations.DeleteModel(
            name="EmailTemplate",
        ),
        migrations.DeleteModel(
            name="SentEmail",
        ),
    ]
