# Generated by Django 4.2 on 2026-06-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["model_name", "action"], name="activity_ac_model_n_4526d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "created_at"], name="activity_ac_user_id_4cbf84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["created_at"], name="activity_ac_created_a8727e_idx"
            ),
        ),
    ]
