# Generated by Django 4.2 on 2026-06-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
