# Generated by Django 4.2 on 2026-06-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0002_interview_score"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["status", "scheduled_at"], name="interviews__status_39545c_idx"
            ),
        ),
    ]
