# Generated by Django 4.2 on 2026-06-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submittals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittal",
            name="is_shortlisted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
