# Generated by Django 4.2 on 2026-06-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submittals", "0002_add_is_shortlisted_to_submittal"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittal",
            name="match_score",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, null=True
            ),
        ),
    ]
