# Generated by Django 4.2 on 2026-06-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submittals", "0005_rebuild_demo_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittal",
            name="rejection_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("salary", "Salary mismatch"),
                    ("experience", "Insufficient experience"),
                    ("technical", "Technical fit"),
                    ("culture", "Culture fit"),
                    ("other", "Other"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
