# Generated by Django 4.2 on 2026-06-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submittals", "0006_add_rejection_reason"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="submittal",
            index=models.Index(
                fields=["status", "updated_at"], name="submittal_status_updated_idx"
            ),
        ),
    ]
